### PR TITLE
Fixes for BeatSaber 0.12.0p1 & other bugs

### PR DESCRIPTION
**Pull request by nicoco007**
Fixes camera sometimes not spawning properly when compiled against 0.12.0p1 & fixes issue #12.

~There is however still a lag issue that occurs after returning multiple times from a song to the main menu; currently investigating that.~ Fixed the lag issue. `CameraMoverPointer` instances were being created when one already existed, which eventually caused lag (at around 50 instances on my computer it got very noticeable).

I also took the liberty of simplifying the 3rd person camera repositioning system since it was a bit confusing and there was some code duplication here and there, but that can be reverted if it isn't deemed appropriate.

### CODE REVIEW

**Comment by Thynix** [comment]
I've tested these changes and they seem to work fine.

**Comment by Thynix** [comment]
I spoke too soon - maybe I built it wrong, but the view is black for me in-song with these changes when using Beat Saber 0.12.2.

**Comment by nicoco007** [comment]
Weird - that's exactly what these changes are supposed to fix. What other plugins are you using?

**Comment by Thynix** [comment]
Oops - my mistake. I managed to not change which branch I was using before building and therefore was testing `v2.0.1`. I've now built your `0.12.0-fixes` - specifically `v2.0.1-8-g8e99125` - and it does indeed fix the monitor view during gameplay.

(For postmortem purposes: I think what happened is I used the GitHub Desktop clone button in the web  UI with your branch selected, and it didn't check out that branch like I expected but didn't check for.)

**Comment by Thynix** [comment]
Looks like this fork is no longer active, and judging by Beat Saber Mod Manager, the community is going with [this fork](https://github.com/brian91292/CameraPlus).

**Comment by nicoco007** [comment]
Yep. It looks like Brian fixed the issue on his end already so I'll just close this PR.

**Pull request closed without merging**
